eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
legacy:
  validate-token:
    uri: http://localhost:9999/auth/validate-token
  get-status-by-customer-borrower-id:
    uri: http://localhost:9999/bo/v2/loans/customer/status/
microservice:
  scoring-service:
    get-scoring:
      uri: http://scoring-service/bo/scoring
  auth-service:
    validate-token:
      uri: http://auth-service/auth/validate-token
