eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
microservice:
  scoring-service:
    get-scoring:
      uri: http://scoring-service/bo/scoring
  auth-service:
    validate-token:
      uri: http://auth-service/auth
